  version: 0.2

  phases:
    build:
      commands:
        - mvn clean package

  post_build:
    commands:
      - echo Built Cleanly

  artifacts:
    files:
      - target/console-bank-0.0.1-SNAPSHOT.jar
