  version: 2.0

  phases:
    build:
      commands:
        - mvn clean && mvn verify

  post_build:
    commands:
      - mv target/*.jar ./console-bank-0.0.1-SNAPSHOT.jar

  artifacts:
    files:
      - console-bank-0.0.1-SNAPSHOT.jar
